# Actions index

<!-- This file is AUTOGENERATED from docblocks in Codice source. DO NOT modify it directly -->

<table class="table docs-index">
    <tr><th>Action hook</th> <th>Description</th> <th>Parameters</th> <th>Defined in</th></tr>
    <?php foreach ($data as $action): ?>
    <tr>
        <td><code><?= $action['name'] ?></code></td>
        <td><?= $action['description'] ?></td>
        <td>
        <?php if (!empty($action['parameters'])): ?>
        <?php foreach ($action['parameters'] as $param): ?>
            <strong><?= $param['name'] ?></strong> (<em><?= $param['type'] ?></em>): <?= $param['description'] ?><br>
        <?php endforeach; ?>
        <?php else: ?>
        none
        <?php endif; ?>
        </td>
        <td data-toggle="tooltip" title="<?= $action['pathDefined'] ?>">
            <?= $action['fileDefined'] ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
