# Filters index

<!-- This file is AUTOGENERATED from docblocks in Codice source. DO NOT modify it directly -->

Note that in case of filters there is always at least one parameter, being
content the filter is applied to. This table omits them and lists only
additional parameters available through array sent as second argument
to the defined callable.

<table class="table docs-index">
    <tr><th>Filter hook</th> <th>Description</th> <th>Parameters</th> <th>Should return</th> <th>Defined in</th></tr>
    <?php foreach ($data as $filter): ?>
    <tr>
        <td><code><?= $filter['name'] ?></code></td>
        <td><?= $filter['description'] ?></td>
        <td>
        <?php if (!empty($filter['parameters'])): ?>
        <?php foreach ($filter['parameters'] as $param): ?>
            <strong><?= $param['name'] ?></strong> (<em><?= $param['type'] ?></em>): <?= $param['description'] ?><br>
        <?php endforeach; ?>
        <?php else: ?>
        none
        <?php endif; ?>
        </td>
        <td><em><?= $filter['returns'] ? $filter['returns'] : '>unknown' ?></em></td>
        <td data-toggle="tooltip" title="<?= $filter['pathDefined'] ?>">
            <?= $filter['fileDefined'] ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
